name: SimpleSpleef
main: SimpleSpleef\Main
version: 1.0.0
api: [1.6.0]
author: SuperChipsLP
description: A Spleef Plugin for PocketMine-MP
commands:
 ss:
  description: Admin commands for SimpleSpleef
  permission: simplespleef.arena.admin
  usage: Visit the documentation for more info
permissions:
  simplespleef.arena.admin:
   default: op
   description: Allows you to create/edit arenas