# How long should an arena wait for players?
wait: 60

# How many players are allowed in an arena
maxplayers: 8

# Surface material (Block that can be destroyed while in an arena
surface: 80

# Ground material (Player looses if lands on this block)
ground: 35